#!/bin/bash

DIR=$(cd $(dirname "$0"); pwd)

test -f /usr/lib/package-drone-server/profile && . /usr/lib/package-drone-server/profile
test -f /etc/default/package-drone-server && . /etc/default/package-drone-server

JAVA="java"

if [ -n "$JAVA_HOME" ]; then
    JAVA="$JAVA_HOME/bin/java"
fi

echo "Using Java: $JAVA"
echo "   Options: $JAVA_OPTS"

if [ -n "$PIDFILE" ]; then
    echo $$ > "$PIDFILE"
    echo "   PID File: $PIDFILE"
fi

exec "$JAVA" $JAVA_OPTS -Dosgi.requiredJavaVersion=1.8 -jar "$DIR"/plugins/org.eclipse.equinox.launcher_*.jar -console -consoleLog "$@"
