DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    ID              VARCHAR(36) NOT NULL,
    NAME            VARCHAR(256),
    
    REG_DATE        DATETIME NOT NULL,
    
    PASSWORD_HASH   VARCHAR(128),
    PASSWORD_SALT   VARCHAR(128),
    
    EMAIL           VARCHAR(256),
    
    EMAIL_TOK       VARCHAR(128),
    EMAIL_TOK_SALT  VARCHAR(128),
    EMAIL_TOK_TS    DATETIME,
    
    EMAIL_VERIFIED  BOOLEAN NOT NULL DEFAULT 0,
    
    DELETED         BOOLEAN NOT NULL DEFAULT 0,
    LOCKED          BOOLEAN NOT NULL DEFAULT 0,
    
    REM_TOKEN_HASH  VARCHAR(256),
    REM_TOKEN_SALT  VARCHAR(128),
    
    PRIMARY KEY ( ID ),
    
    UNIQUE ( EMAIL )
);