@ALTER TABLE USERS DROP COLUMN ROLES;

ALTER TABLE USERS ADD COLUMN ROLES CLOB(1M);

ALTER TABLE USERS MODIFY COLUMN PASSWORD_HASH VARCHAR(64);
ALTER TABLE USERS MODIFY COLUMN PASSWORD_SALT VARCHAR(64);
ALTER TABLE USERS MODIFY COLUMN EMAIL_TOK VARCHAR(64);
ALTER TABLE USERS MODIFY COLUMN EMAIL_TOK_SALT VARCHAR(64);
ALTER TABLE USERS MODIFY COLUMN REM_TOKEN_HASH VARCHAR(64);
ALTER TABLE USERS MODIFY COLUMN REM_TOKEN_SALT VARCHAR(64);