ALTER TABLE USERS MODIFY ROLES LONGTEXT;

ALTER TABLE EXT_CHAN_PROPS MODIFY "VALUE" LONGTEXT;
ALTER TABLE PROV_CHAN_PROPS MODIFY "VALUE" LONGTEXT;

ALTER TABLE EXT_ART_PROPS MODIFY "VALUE" LONGTEXT;
ALTER TABLE PROV_ART_PROPS MODIFY "VALUE" LONGTEXT;