ALTER TABLE JOBS ADD COLUMN CURRENT_WORK_LABEL  VARCHAR(255);
ALTER TABLE JOBS ADD COLUMN PERCENT_COMPLETE    FLOAT;

ALTER TABLE CHANNELS ADD COLUMN DESCRIPTION   VARCHAR(255);

DROP TABLE IF EXISTS CHANNEL_CACHE;
CREATE TABLE CHANNEL_CACHE (
    CHANNEL_ID    VARCHAR(36) NOT NULL,
    
    NS            VARCHAR(255) NOT NULL,
    "KEY"         VARCHAR(255) NOT NULL,
    
    NAME          VARCHAR(255),
    MIME_TYPE     VARCHAR(255) NOT NULL DEFAULT 'application/octet-stream',
    SIZE          NUMERIC NOT NULL,
    
    DATA          LONGBLOB,
    
    PRIMARY KEY ( CHANNEL_ID, NS, "KEY" ),
    
    FOREIGN KEY ( CHANNEL_ID ) REFERENCES CHANNELS(ID) ON DELETE CASCADE
);
