ALTER TABLE CHANNEL_CACHE ADD COLUMN CREATION_TS TIMESTAMP;

-- required for MySQL

UPDATE CHANNEL_CACHE SET CREATION_TS = CURRENT_TIMESTAMP;

--#ifdef postgres
ALTER TABLE CHANNEL_CACHE ALTER COLUMN CREATION_TS SET NOT NULL;
--#endif -- postgres

--#ifdef mysql
ALTER TABLE CHANNEL_CACHE MODIFY COLUMN CREATION_TS TIMESTAMP NOT NULL;
--#endif -- mysql