ALTER TABLE PROPERTIES ADD COLUMN NS VARCHAR(255);

UPDATE PROPERTIES SET NS = 'core';

--#ifdef postgres
ALTER TABLE PROPERTIES ALTER COLUMN NS SET NOT NULL;
ALTER TABLE PROPERTIES DROP CONSTRAINT PROPERTIES_PKEY;
ALTER TABLE PROPERTIES ADD PRIMARY KEY (NS, "KEY");
--#endif -- postgres

--#ifdef mysql
ALTER TABLE PROPERTIES MODIFY COLUMN NS VARCHAR(255) NOT NULL;
ALTER TABLE PROPERTIES DROP PRIMARY KEY, ADD PRIMARY KEY(NS, "KEY");
--#endif -- mysql