CREATE TABLE CHANNELS (
	ID			VARCHAR(36) NOT NULL,
	
	PRIMARY KEY (ID)
);

CREATE TABLE ARTIFACTS (
	ID			VARCHAR(36) NOT NULL,
	CHANNEL_ID		VARCHAR(36) NOT NULL,
	
	NAME		VARCHAR(255) NOT NULL,
	
	DATA		LONGBLOB,
	SIZE		NUMERIC NOT NULL,
	
 	PRIMARY KEY (ID),
 	FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNELS(ID)	
);

CREATE TABLE ARTIFACT_PROPERTIES (
	ART_ID		VARCHAR(36) NOT NULL,
	`NS`		VARCHAR(255) NOT NULL,
	`KEY`		VARCHAR(255) NOT NULL,
	`VALUE`		TEXT,
	
	PRIMARY KEY (ART_ID, `NS`, `KEY` )
);

CREATE TABLE CHANNEL_ASPECTS (
	CHANNEL_ID	VARCHAR(36) NOT NULL,
	ASPECT		VARCHAR(255) NOT NULL,
	
	FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNELS(ID)
);