DROP TABLE IF EXISTS VIRTUAL_ARTIFACTS;
DROP TABLE IF EXISTS GENERATED_ARTIFACTS;
DROP TABLE IF EXISTS EXT_ART_PROPS;
DROP TABLE IF EXISTS PROV_ART_PROPS;
DROP TABLE IF EXISTS ARTIFACTS;
DROP TABLE IF EXISTS CHANNEL_ASPECTS;
DROP TABLE IF EXISTS CHANNELS;