ALTER TABLE ARTIFACTS
    ADD COLUMN `TYPE` VARCHAR(8) NOT NULL;
	
UPDATE ARTIFACTS SET `TYPE`='S';

CREATE TABLE VIRTUAL_ARTIFACTS (
    ID            VARCHAR(36) NOT NULL,
    
    PARENT        VARCHAR(36),
    
    NS            VARCHAR(255) NOT NULL,
    
    PRIMARY KEY (ID),
    FOREIGN KEY (PARENT) REFERENCES ARTIFACTS(ID)
);

CREATE TABLE PROV_ART_PROPS (
    ART_ID        VARCHAR(36) NOT NULL,
    `NS`          VARCHAR(255) NOT NULL,
    `KEY`         VARCHAR(255) NOT NULL,
    `VALUE`       TEXT,
    
    PRIMARY KEY ( ART_ID, `NS`, `KEY` ),
    FOREIGN KEY ( ART_ID ) REFERENCES ARTIFACTS(ID)
);

RENAME TABLE ARTIFACT_PROPERTIES to EXT_ART_PROPS;

ALTER TABLE CHANNELS ADD COLUMN NAME VARCHAR(255) UNIQUE;